# Site settings
title: Unbounded...
email: matthew.nuckolls@gmail.com
author: Matthew Nuckolls
description: "A blog of indeterminate value"
baseurl: ""
url: "http://unbounded.mnuck.com"
google_analytics:
animated: true
show_related_posts: false
exclude: [LICENSE.txt, s3_website.yml, command_help]

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
